# tools and scripts
path:
# 更改工具路径
  samtools: ../../tools/samtools/samtools
  hisat3n: ../../tools/hisat-3n/hisat-3n
  hisat3ntable: ../../tools/hisat-3n/hisat-3n-table
  umicollapse: ../../../.miniconda3/envs/snakemake/share/umicollapse-1.1.0-0/umicollapse.jar
  bgzip: ../../tools/htslib/bgzip
# 修改结束

  join_pileup.py: ../bin/join_pileup.py
  group_pileup.py: ../bin/group_pileup.py
  select_sites.py: ../bin/select_sites.py
  filter_sites.py: ../bin/filter_sites.py

# global config
#
# prepare genes index
# premap to rRNA, tRNA and other small RNA
# If study virus, then also premap to virus genome
# customized_genes:
#   - a.fa
#   - b.fa
# library: ILLUMINARNA
library: INLINE
makedup: false

# reference genome and index
reference:
  contamination:
    fa: ../../data/reference/fastq/contamination.fa
    hisat3n: ../../data/reference/index/contamination
  genes:
    fa: ../../data/reference/fastq/gencode.v47.lncRNA_transcripts.fa
    hisat3n: ../../data/reference/index/gencode.v47.lncRNA_transcripts
  genome:
    fa: ../../data/reference/fastq/GRCh38.primary_assembly.genome.fa
    hisat3n: ../../data/reference/index/GRCh38.primary_assembly.genome

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  WT-rep1:
    data:
      - R1: ../../data/samples/SRR23538292.fastq.gz
    group: DRUG
  WT-rep2:
    data:
      - R1: ../../data/samples/SRR23538291.fastq.gz
    group: DRUG
  WT-rep3:
    data:
      - R1: ../../data/samples/SRR23538290.fastq.gz
    group: DRUG
