# tools and scripts
path:
# 更改工具路径
  samtools: ../tools/samtools/samtools
  hisat3n: ../tools/hisat-3n/hisat-3n
  hisat3ntable: ../tools/hisat-3n/hisat-3n-table
# 修改结束

  join_pileup.py: ../bin/join_pileup.py
  group_pileup.py: ../bin/group_pileup.py
  select_sites.py: ../bin/select_sites.py
  filter_sites.py: ../bin/filter_sites.py

# global config
#
# prepare genes index
# premap to rRNA, tRNA and other small RNA
# If study virus, then also premap to virus genome
# customized_genes:
#   - a.fa
#   - b.fa
# 启用全局配置
library: INLINE
makedup: false
# 结束更改

# reference genome and index
reference:
# 去除污染物的参考数据库
  # contamination:
  #   fa: ~/reference/genome/contamination/contamination.fa
  #   hisat3n: ~/reference/index/hisat3n/contamination/contamination
# 修改结束
  genes:
    fa: ~/reference/genome/Homo_sapiens.GRCh38.sncRNA.fa
    hisat3n: ~/reference/index/hisat3n/Homo_sapiens.GRCh38.sncRNA/Homo_sapiens.GRCh38.sncRNA
  genome:
    fa: ~/reference/genome/Homo_sapiens.GRCh38.genome.fa
    hisat3n: ~/reference/index/hisat3n/Homo_sapiens.GRCh38.genome/Homo_sapiens.GRCh38.genome

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  CONTROL-rep1:
    data:
      - R1: ../data/test1_R1.fq.gz
        R2: ../data/test1_R2.fq.gz
    group: CONTROL
  DRUG-rep1:
    data:
      - R1: ../data/test2_R1.fq.gz
    group: DRUG
  DRUG-rep2:
    data:
      - R1: ../data/test3_R1.fq.gz
        R2: ../data/test3_R2.fq.gz
    group: DRUG
