# tools and scripts
path:
# 更改工具路径
  samtools: ../../tools/samtools/samtools
  hisat3n: ../../tools/hisat-3n/hisat-3n
  hisat3ntable: ../../tools/hisat-3n/hisat-3n-table
# 修改结束

  join_pileup.py: ../bin/join_pileup.py
  group_pileup.py: ../bin/group_pileup.py
  select_sites.py: ../bin/select_sites.py
  filter_sites.py: ../bin/filter_sites.py

# global config
#
# prepare genes index
# premap to rRNA, tRNA and other small RNA
# If study virus, then also premap to virus genome
# customized_genes:
#   - a.fa
#   - b.fa
library: TAKARAV3
makedup: false

# reference genome and index
reference:
  contamination:
    fa: ../../reference/genome/GCF_000008865.2_ASM886v2_genomic.fna
    hisat3n: ../../reference/index/GCF_000008865.2_ASM886v2_genomic/GCF_000008865.2_ASM886v2_genomic
  genes:
    fa: ../../reference/genome/Homo_sapiens.GRCh38.ncrna.fa
    hisat3n: ../../reference/index/Homo_sapiens.GRCh38.ncrna/Homo_sapiens.GRCh38.ncrna
  genome:
    fa: ../../reference/genome/GCF_000001405.40_GRCh38.p14_genomic.fna
    hisat3n: ../../reference/index/GCF_000001405.40_GRCh38.p14_genomic/GCF_000001405.40_GRCh38.p14_genomic

# Sample name should be indentical and listed in the 2nd level of the yaml file
# Each sample will be analysis seperately, but
# samples sharing the same group id will be regared as biological replicates and combined in the comparing step
samples:
  WT-rep1:
    data:
      - R1: ../../data/SRR23538292.fastq.gz
    group: DRUG
  WT-rep2:
    data:
      - R1: ../../data/SRR23538291.fastq.gz
    group: DRUG
  WT-rep3:
    data:
      - R1: ../../data/SRR23538290.fastq.gz
    group: DRUG
